Description: This template creates a vpc with an Internet Gateway, with Public and Private Subnets
# Added Public Route, PublicRouteTable and SecurityGroup


Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      Tags:
        - Key: Name
          Value: Jason Kelly Lab Portfolio 1 Project
          
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: J.Kelly Lab Portfolio 1 IGW
   
   VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
      
    PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub 
      - ${AWS::Region}${AZ}
      - AZ: !Select 
          - 0
          - !Ref VpcAvailabilityZone
      CidrBlock: 10.0.1.0/24

    PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub 
      - ${AWS::Region}${AZ}
      - AZ: !Select 
          - 0
          - !Ref VpcAvailabilityZone
      CidrBlock: 10.0.10.0/24
      
    PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

    RouteToPublic:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet
      
    SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow Https and SSH connections
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/24
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/24