Description: This template creates a vpc with an Internet Gateway, with Public and Private Subnets

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      Tags:
        - Key: Name
          Value: Jason Kelly Lab Portfolio 1 Project
          
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: J.Kelly Lab Portfolio 1 IGW
   
   VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
      
    PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub 
      - ${AWS::Region}${AZ}
      - AZ: !Select 
          - 0
          - !Ref VpcAvailabilityZone
      CidrBlock: 10.0.1.0/24

    PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Sub 
      - ${AWS::Region}${AZ}
      - AZ: !Select 
          - 0
          - !Ref VpcAvailabilityZone
      CidrBlock: 10.0.10.0/24